# Site settings
title: "{ code2 blog }"
email: hello@code2.co
description: > 
  Code2 Software blog on agile web development, Ruby, Rails, products, user experiences, new technologies.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: code2co
github_username:  code2co

# Build settings
markdown: kramdown
